#!/bin/sh

#dvv/schema.js:schema
#akidee/underscorex:underscorex
#SteveSanderson/knockout/build/output/knockout-latest.debug.js:knockout.js
#SteveSanderson/knockout.mapping/build/output/knockout.mapping-latest.debug.js:knockout.mapping.js

deps='
cloudhead/eyes.js/lib/eyes.js:eyes.js
kriszyp/promised-io/lib:promised-io
dvv/json-schema:json-schema
kriszyp/compose/lib/compose.js:compose.js
documentcloud/underscore/underscore.js:underscore.js
douglascrockford/JSON-js/json2.js:json2.js
documentcloud/backbone/backbone.js:backbone.js
jquery/jquery-tmpl/jquery.tmpl.js:jquery.tmpl.js
dvv/rql/lib:rql
dvv/node-formidable/lib/formidable:formidable
maqr/node-xml2js/lib:xml2js
astro/node-expat/build/default/node-expat.node:node-expat.node
Poetro/node-xml2js-expat/lib/xml2js.js:xml2js.js
tautologistics/node-htmlparser/lib/htmlparser.js:htmlparser.js
isaacs/sax-js/lib/sax.js:sax.js
dvv/coffee-mongo/lib:mongo
mranney/node_redis:redis
cloudhead/node-static/lib:static
jed/cookie-node/index.js:cookie.js
bentomas/node-mime:mime
3rd-eden/node-useragent/useragent.js:useragent.js
weaver/node-mail/lib/mail:mail
miksago/node-websocket-server/lib:ws-server
learnboost/socket.io-node:io
Marak/Faker.js:faker
'

#deps=dvv/rql/lib:rql

lib=lib/node
mkdir -p "$lib"
for dep in $deps; do
	# parse definition
	path=${dep%:*}
	link=${dep##*:}
	author=${path%%/*}
	path=${path#*/}
	git=${path%%/*}
	# fetch the package
	echo link ${author}\'s $git to $link, path $path
	if ! test -d git/${git}; then
		#git clone https://github.com/${author}/${git}.git git/${git}
		mkdir -p git/${git}
		wget -ct3 -q --progress=bar --no-check-certificate http://nodeload.github.com/${author}/${git}/tarball/master -O- | tar -xzf- --strip 1 -C git/${git}
		cd git/${git}
		#if test -f Makefile; then
		#	make
		#fi
		if test -f wscript; then
			node-waf configure build
		fi
		cd ../..
	fi
	# symlink entry point
	test -e "$lib/$link" || ln -s "../../git/$path" "$lib/$link"
done
