#!/bin/sh

cat \
	../../lib/node/json2.js \
	../../lib/node/es5-shim.js \
	../../lib/node/underscore.js \
	../../lib/node/underscore.string.js \
	../../lib/node/jquery.tmpl.js \
	../../lib/node/backbone.js \
	jquery.textchange.min.js \
	formdeserialize.js \
	\
 > bundle.js
#| build/jsmin > bundle.js

exit 0

cat \
	../../lib/node/json2.js \
	../../lib/node/underscore.js \
	../../lib/node/backbone.js \
	../../lib/node/jquery.tmpl.js \
	../../lib/node/knockout.js \
	jquery.textchange.min.js \
	../../lib/node/knockout.mapping.js \
	formdeserialize.js \
	\
 > bundle.js
#| build/jsmin > bundle.js

